server:
    port: 8080
eureka:
   client:
      service-url:
       defaultZone: http://localhost:8761/eureka/

spring:
     application:
               name: ApiGateWayForService
     cloud:
        gateway:
             routes:
               - id: Flight_JWTService
                 uri: http://localhost:8083/
                 predicates:
                 - Path=/api/jwt/**
               - id: AdminFlight
                 uri: http://localhost:8081/
                 predicates:
                  - Path=/api/admin/**
               - id: FlightBooking
                 uri: http://localhost:8082/
                 predicates:
                 - Path=/api/book/**  