server:
    port: 8081
eureka:
    client:
        service-url:
                 defaultZone: http://localhost:8761/eureka/       
spring:
    application:
           name: AdminFlight
    data:
        mongodb:
             uri: mongodb+srv://vishessh1997:vis123@cluster0.klrox.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
             
logging:
  file: 
    path: /my-logs/app.log
    name: log.txt
jwt:
  secret: secrectkey123
  