jwt:
  secret: secrectkey123

server:
    port: 8083        
    
    
spring:
    application:
           name: Flight_JWTService
    data:
        mongodb:
             uri: mongodb+srv://vishessh1997:vis123@cluster0.klrox.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
eureka:
     client:
          service-url:
                   defaultZone: http://localhost:8761/eureka/          
                          
logging:
  file: 
    path: /my-logs/app.log
    name: log.txt  
    
data:
   exception:
          incmsg: Invalid Credentials!!
            